# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2f4bae7964a8e7e65989c0abd425af8017f453529439c032f25539aadfec3742d3deb708ffaf73d3b943a20497988b7d051bc37f1ef6d11222b3a4fba1ec21cf

test:
  secret_key_base: 5533eaeefc942cd45cb98256157e20323e18ae145ee32654e07a106225ca163149f75986fb915f6e6bcedc1df7bcbd5266e2676aa4a79028be486417dd2fcaa2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
